import { Routes,Route,Navigate,useLocation } from "react-router-dom";
import { useEffect } from "react";
import Navbar from "./components/Navbar"; import Footer from "./components/Footer"; import Home from "./pages/Home"; import Products from "./pages/Products"; import ProductDetails from "./pages/ProductDetails"; import Wishlist from "./pages/Wishlist"; import Login from "./pages/Login"; import Register from "./pages/Register"; import ForgotPassword from "./pages/ForgotPassword"; import Account from "./pages/Account"; import Subscription from "./pages/Subscription"; import Collections from "./pages/Collections"; import Resources from "./pages/Resources"; import About from "./pages/About"; import Admin from "./pages/Admin"; import AdminLogin from "./pages/AdminLogin"; import NotFound from "./pages/NotFound"; import { useAuth } from "./hooks/useAuth";

// React Router doesn't reset scroll position on navigation. Without this, clicking
// a card while scrolled down on /products leaves you scrolled to the same offset on
// the new (often shorter) page — looking like it "jumped to the bottom".
function ScrollToTop(){const{pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0)},[pathname]);return null}

function AdminGuard(){const{user,loading}=useAuth();const location=useLocation();if(loading)return <main className="simple-page container"><p>Checking admin access…</p></main>;if(!user||user.role!=="admin")return <Navigate to={`/admin/login?next=${encodeURIComponent(location.pathname)}`} replace/>;return <Admin/>}
function Shell(){const location=useLocation();const adminArea=location.pathname.startsWith("/admin");return <><ScrollToTop/>{!adminArea&&<Navbar/>}<Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/products/boilerplates" element={<Navigate to="/products?category=Boilerplates" replace/>}/><Route path="/products/:slug" element={<ProductDetails/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/account" element={<Account/>}/><Route path="/subscription" element={<Subscription/>}/><Route path="/collections/:collection" element={<Collections/>}/><Route path="/resources/*" element={<Resources/>}/><Route path="/about" element={<About/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin/*" element={<AdminGuard/>}/><Route path="*" element={<NotFound/>}/></Routes>{!adminArea&&<Footer/>}</>}
export default function App(){return <Shell/>}
