import { useState } from "react";
import { Link,useNavigate } from "react-router-dom";
import { api } from "../services/api";
import PasswordField from "../components/PasswordField";
import { useDocumentTitle } from "../hooks/useDocumentTitle";

export default function ForgotPassword(){
 const[step,setStep]=useState("email");const[email,setEmail]=useState("");const[otp,setOtp]=useState("");const[resetToken,setResetToken]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[devOtp,setDevOtp]=useState("");const nav=useNavigate();useDocumentTitle("Reset password");
 async function send(e,resend=false){e.preventDefault();setError("");setMessage("");setLoading(true);try{const x=resend?await api.auth.resendOtp({email}):await api.auth.forgot({email});setMessage(x.message);setDevOtp(x.devOtp||"");if(!resend)setStep("otp")}catch(err){setError(err.message)}finally{setLoading(false)}}
 async function verify(e){e.preventDefault();setError("");setLoading(true);try{const x=await api.auth.verifyOtp({email,otp});setResetToken(x.resetToken);setStep("password")}catch(err){setError(err.message)}finally{setLoading(false)}}
 async function reset(e){e.preventDefault();setError("");if(password.length<8)return setError("Password must be at least 8 characters.");if(password!==confirm)return setError("Passwords do not match.");setLoading(true);try{await api.auth.resetPassword({resetToken,password});setMessage("Password changed successfully.");setStep("done")}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <main className="auth-page"><div className="auth-card"><span className="eyebrow">ACCOUNT RECOVERY</span><h1>{step==="done"?"Password updated.":"Reset your password."}</h1><p>{step==="email"?"We’ll send a 6-digit verification code to your registered email.":step==="otp"?`Enter the code sent to ${email}.`:step==="password"?"Choose a new password for your account.":"Your account is ready. Sign in with your new password."}</p>{error&&<div className="form-error" role="alert">{error}</div>}{message&&step!=="done"&&<div className="success-state">{message}</div>}{step==="email"&&<form onSubmit={send}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="button primary" disabled={loading}>{loading?"Sending…":"Send OTP"}</button></form>}{step==="otp"&&<><form onSubmit={verify}><label>Verification code<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="123456"/></label>{devOtp&&<div className="success-state">Development OTP: <strong>{devOtp}</strong></div>}<button className="button primary" disabled={loading}>{loading?"Verifying…":"Verify OTP"}</button></form><button className="auth-link auth-button-link" onClick={e=>send(e,true)} disabled={loading}>Resend OTP</button></>}{step==="password"&&<form onSubmit={reset}><PasswordField label="New password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} placeholder="Minimum 8 characters" autoComplete="new-password"/><PasswordField label="Confirm password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} placeholder="Repeat password" autoComplete="new-password"/><button className="button primary" disabled={loading}>{loading?"Saving…":"Change password"}</button></form>}{step==="done"&&<button className="button primary" onClick={()=>nav("/login")}>Back to sign in</button>}<Link to="/login" className="auth-link">Back to sign in →</Link></div></main>
}
