import { Router } from "express";import crypto from "crypto";import Product from "../models/Product.js";import Order from "../models/Order.js";import Download from "../models/Download.js";import { authRequired,adminRequired } from "../middleware/auth.js";
const router=Router();
function numericAmount(product){if(Number(product.priceAmount)>0)return Number(product.priceAmount);return Number(String(product.price||"").replace(/[^0-9.]/g,""))||0}
router.get("/mine",authRequired,async(req,res,next)=>{try{res.json({orders:await Order.find({user:req.user.id}).populate("items.product","name slug version").sort({createdAt:-1})})}catch(e){next(e)}});
router.post("/checkout",authRequired,async(req,res,next)=>{try{const slug=String(req.body.slug||"");const product=await Product.findOne({slug,isPublished:true});if(!product)return res.status(404).json({message:"Product not found."});if(product.productType==="FREE")return res.status(400).json({message:"Free products do not require checkout."});const amount=Math.round(numericAmount(product)*100);if(!amount)return res.status(400).json({message:"This product has no payable amount configured."});if(process.env.PAYMENT_PROVIDER!=="razorpay")return res.status(503).json({message:"Live payment is not configured. Set PAYMENT_PROVIDER=razorpay and configure Razorpay keys."});const auth=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString("base64");const response=await fetch("https://api.razorpay.com/v1/orders",{method:"POST",headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/json"},body:JSON.stringify({amount,currency:product.currency||"INR",receipt:`cf_${Date.now()}`,notes:{productId:product._id.toString(),userId:req.user.id}})});const data=await response.json().catch(()=>({}));if(!response.ok)return res.status(502).json({message:data.error?.description||"Payment provider error."});const order=await Order.create({user:req.user.id,items:[{product:product._id,nameSnapshot:product.name,amount:numericAmount(product),quantity:1}],totalAmount:numericAmount(product),currency:product.currency||"INR",status:"pending",provider:"razorpay",providerPaymentId:data.id});res.status(201).json({orderId:order._id.toString(),razorpayOrderId:data.id,amount,currency:product.currency||"INR",keyId:process.env.RAZORPAY_KEY_ID})}catch(e){next(e)}});
router.post("/checkout/verify",authRequired,async(req,res,next)=>{try{const{orderId,razorpayOrderId,razorpayPaymentId,razorpaySignature}=req.body;const order=await Order.findOne({_id:orderId,user:req.user.id,provider:"razorpay"});if(!order)return res.status(404).json({message:"Order not found."});const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(`${razorpayOrderId}|${razorpayPaymentId}`).digest("hex");if(expected!==razorpaySignature)return res.status(400).json({message:"Payment signature verification failed."});order.status="paid";order.providerPaymentId=razorpayPaymentId;await order.save();for(const item of order.items){const product=await Product.findById(item.product);if(product){product.downloadCount=String((parseInt(product.downloadCount||"0",10)||0)+1);await product.save()}await Download.findOneAndUpdate({user:req.user.id,product:item.product,order:order._id},{user:req.user.id,product:item.product,order:order._id,version:product?.version||"1.0.0"},{upsert:true,new:true,setDefaultsOnInsert:true})}res.json({message:"Payment verified.",order})}catch(e){next(e)}});
router.post("/demo",authRequired,async(req,res,next)=>{try{const slugs=req.body.slugs||[];const products=await Product.find({slug:{$in:slugs},isPublished:true});if(!products.length)return res.status(400).json({message:"No products selected."});const items=products.map(p=>({product:p._id,nameSnapshot:p.name,amount:numericAmount(p),quantity:1}));const total=items.reduce((sum,item)=>sum+item.amount*item.quantity,0);const order=await Order.create({user:req.user.id,items,totalAmount:total,currency:"INR",status:"paid",provider:"demo"});for(const item of items){const product=products.find(x=>x._id.toString()===item.product.toString());if(product){product.downloadCount=String((parseInt(product.downloadCount||"0",10)||0)+1);await product.save()}await Download.create({user:req.user.id,product:item.product,order:order._id,version:product?.version||"1.0.0"})}await order.populate("items.product","name slug version");res.status(201).json({order})}catch(e){next(e)}});
router.get("/admin/all",authRequired,adminRequired,async(req,res,next)=>{try{res.json({orders:await Order.find().populate("user","name email").populate("items.product","name slug").sort({createdAt:-1})})}catch(e){next(e)}});
router.put("/admin/:id",authRequired,adminRequired,async(req,res,next)=>{try{const order=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!order)return res.status(404).json({message:"Order not found."});res.json({order})}catch(e){next(e)}});
export default router;
