const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
function normalizeProduct(product){if(!product)return product;return product.previewCode?{...product,previewMode:"source"}:product}
async function request(path,options={}){const token=localStorage.getItem("codefusion_token");const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API}${path}`,{...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message||"Request failed.");error.status=response.status;error.code=data.code;error.remaining=data.remaining;throw error}return data}
export const api={
 base:API,
 auth:{login:(body)=>request("/auth/login",{method:"POST",body:JSON.stringify(body)}),adminLogin:(body)=>request("/auth/admin-login",{method:"POST",body:JSON.stringify(body)}),register:(body)=>request("/auth/register",{method:"POST",body:JSON.stringify(body)}),forgot:(body)=>request("/auth/forgot-password",{method:"POST",body:JSON.stringify(body)}),resendOtp:(body)=>request("/auth/resend-otp",{method:"POST",body:JSON.stringify(body)}),verifyOtp:(body)=>request("/auth/verify-otp",{method:"POST",body:JSON.stringify(body)}),resetPassword:(body)=>request("/auth/reset-password",{method:"POST",body:JSON.stringify(body)}),me:()=>request("/auth/me"),update:(body)=>request("/auth/me",{method:"PUT",body:JSON.stringify(body)})},
 products:{list:async(params="")=>{const result=await request(`/products${params}`);result.products=(result.products||[]).map(normalizeProduct);return result},categories:()=>request("/products/categories"),one:async(slug)=>{const result=await request(`/products/${slug}`);result.product=normalizeProduct(result.product);return result},copyCode:(slug)=>request(`/products/${slug}/copy-code`,{method:"POST"}),copyPrompt:(slug)=>request(`/products/${slug}/copy-prompt`,{method:"POST"}),adminAll:()=>request("/products/admin/all"),create:(body)=>request("/products/admin",{method:"POST",body:JSON.stringify(body)}),update:(id,body)=>request(`/products/admin/${id}`,{method:"PUT",body:JSON.stringify(body)}),duplicate:(id)=>request(`/products/admin/${id}/duplicate`,{method:"POST"}),remove:(id)=>request(`/products/admin/${id}`,{method:"DELETE"})},
 subscription:{get:()=>request("/subscription"),plans:()=>request("/subscription/plans"),balance:()=>request("/subscription/balance"),history:()=>request("/subscription/history"),checkout:()=>request("/subscription/checkout",{method:"POST"}),verify:(body)=>request("/subscription/verify",{method:"POST",body:JSON.stringify(body)}),adminSettings:()=>request("/subscription/admin/settings"),updateAdminSettings:(body)=>request("/subscription/admin/settings",{method:"PUT",body:JSON.stringify(body)}),adminSubscribers:()=>request("/subscription/admin/subscribers"),adminTransactions:()=>request("/subscription/admin/transactions")},
 wishlist:{list:()=>request("/wishlist"),toggle:(slug)=>request(`/wishlist/${slug}`,{method:"POST"})},
 reviews:{list:(slug)=>request(`/reviews/${slug}`),create:(slug,body)=>request(`/reviews/${slug}`,{method:"POST",body:JSON.stringify(body)}),admin:()=>request("/reviews/admin/all"),moderate:(id,status)=>request(`/reviews/admin/${id}`,{method:"PUT",body:JSON.stringify({status})})},
 analytics:{event:(body)=>request("/analytics/event",{method:"POST",body:JSON.stringify(body)}),admin:()=>request("/analytics/admin")},
 admin:{dashboard:()=>request("/admin/dashboard"),summary:()=>request("/admin/summary"),users:()=>request("/admin/users"),categories:()=>request("/admin/categories"),createCategory:(body)=>request("/admin/categories",{method:"POST",body:JSON.stringify(body)}),updateCategory:(id,body)=>request(`/admin/categories/${id}`,{method:"PUT",body:JSON.stringify(body)}),removeCategory:(id)=>request(`/admin/categories/${id}`,{method:"DELETE"}),collections:()=>request("/admin/collections"),createCollection:(body)=>request("/admin/collections",{method:"POST",body:JSON.stringify(body)}),updateCollection:(id,body)=>request(`/admin/collections/${id}`,{method:"PUT",body:JSON.stringify(body)}),removeCollection:(id)=>request(`/admin/collections/${id}`,{method:"DELETE"}),settings:()=>request("/admin/settings"),saveSettings:(settings)=>request("/admin/settings",{method:"PUT",body:JSON.stringify({settings})}),analytics:()=>request("/admin/analytics")}};
